// patterns/splitter-outside-navigator-react/src/Cards.jsx
import React from 'react';
import { Page, Toolbar, ToolbarButton, Icon, ListTitle, List, ListItem } from 'react-onsenui';

import PageNav2 from './PageNav2';

export default class Cards extends React.Component {
  renderToolbar() {
    return (
      <Toolbar>
        <div className='center'>Splitter+Navigator</div>
        <div className='right'>
          <ToolbarButton onClick={this.showMenu.bind(this)}>
            <Icon icon='ion-navicon, material:md-menu' />
          </ToolbarButton>
        </div>
      </Toolbar>
    );
  }

  showMenu() {
    this.props.showMenu();
  }

  pushPage(event) {
    this.props.navigator.pushPage({ component: PageNav2, props: { key: 'pageNav2', cardTitle: event.target.textContent } });
  }

  render() {
    return (
      <Page renderToolbar={this.renderToolbar.bind(this)}>
        <h2>Cards</h2>
        
        <ListTitle>Card List</ListTitle>
        <List>
          <ListItem onClick={this.pushPage.bind(this)}>Card One</ListItem>
          <ListItem onClick={this.pushPage.bind(this)}>Card Two</ListItem>
          <ListItem onClick={this.pushPage.bind(this)}>Card Three</ListItem>
        </List>
        <p style={{ textAlign: 'center', opacity: '0.6', paddingTop: '20px' }}>
          Swipe left to open the menu!
        </p>
      </Page>
    );
  }
}

// patterns/splitter-outside-navigator-vue/src/Cards.vue
<template>
  <v-ons-page>
    <v-ons-toolbar>
      <div class="center">Navigator+Tabbar</div>
      <div class="right">
        <v-ons-toolbar-button @click="openMenu">
          <v-ons-icon icon="md-menu"></v-ons-icon>
        </v-ons-toolbar-button>
      </div>
    </v-ons-toolbar>
    <h2>Cards</h2>
    <v-ons-list-title>Card List</v-ons-list-title>
    <v-ons-list>
      <v-ons-list-item @click="push">Card One</v-ons-list-item>
      <v-ons-list-item @click="push">Card Two</v-ons-list-item>
      <v-ons-list-item @click="push">Card Three</v-ons-list-item>
    </v-ons-list>
    <p style="text-align: center; opacity: 0.6; padding-top: 20px;">
      Swipe left to open the menu!
    </p>
  </v-ons-page>
</template>

<script>
import pageNav2 from './PageNav2';
export default {
  methods: {
    push($event) {
      var cardTitle = $event.target.textContent;
      var pageToPush = {
        extends: pageNav2,
        data() {
          return {
            cardTitle: cardTitle
          }
        }
      };
      this.$emit('push', pageToPush);
    }
  },
  props: ['openMenu']
}
</script>
