// patterns/splitter-outside-navigator-react/src/Home.jsx
import React from 'react';
import { Page, Toolbar, ToolbarButton, Icon, Button } from 'react-onsenui';

import PageNav1 from './PageNav1';

export default class Home extends React.Component {
  renderToolbar() {
    return (
      <Toolbar>
        <div className='center'>Splitter+Navigator</div>
        <div className='right'>
          <ToolbarButton onClick={this.showMenu.bind(this)}>
            <Icon icon='ion-navicon, material:md-menu' />
          </ToolbarButton>
        </div>
      </Toolbar>
    );
  }

  showMenu() {
    this.props.showMenu();
  }

  pushPage() {
    this.props.navigator.pushPage({ component: PageNav1, props: { key: 'pageNav1' } });
  }

  render() {
    return (
      <Page renderToolbar={this.renderToolbar.bind(this)}>
        <h2>Home</h2>
        <div style={{ textAlign: 'center' }}>
          <br />
          <Button onClick={this.pushPage.bind(this)}>
            Push Page
          </Button>
        </div>
        <p style={{ textAlign: 'center', opacity: '0.6', paddingTop: '20px' }}>
          Swipe left to open the menu!
        </p>
      </Page>
    );
  }
}

// patterns/splitter-outside-navigator-vue/src/Home.vue
<template>
  <v-ons-page>
    <v-ons-toolbar>
      <div class="center">Splitter+Navigator</div>
      <div class="right">
        <ons-toolbar-button @click="openMenu">
          <ons-icon icon="md-menu"></ons-icon>
        </ons-toolbar-button>
      </div>
    </v-ons-toolbar>
    <h2>Home</h2>
    <div style="text-align: center">
      <br>
      <v-ons-button @click="push">
        Push Page
      </v-ons-button>
    </div>
    <p style="text-align: center; opacity: 0.6; padding-top: 20px;">
      Swipe left to open the menu!
    </p>
  </v-ons-page>
</template>

<script>
import pageNav1 from './PageNav1';
export default {
  methods: {
    push() {
      this.$emit('push', pageNav1);
    }
  },
  props: ['pageStack', 'openMenu']
}
</script>
