// patterns/splitter-outside-navigator-react/src/Settings.jsx
import React from 'react';
import { Page, Toolbar, ToolbarButton, Icon } from 'react-onsenui';

export default class Settings extends React.Component {
  renderToolbar() {
    return (
      <Toolbar>
        <div className='center'>Splitter+Navigator</div>
        <div className='right'>
          <ToolbarButton onClick={this.showMenu.bind(this)}>
            <Icon icon='ion-navicon, material:md-menu' />
          </ToolbarButton>
        </div>
      </Toolbar>
    );
  }

  showMenu() {
    this.props.showMenu();
  }

  render() {
    return (
      <Page renderToolbar={this.renderToolbar.bind(this)}>
        <h2>Settings</h2>
        <p style={{ textAlign: 'center', opacity: '0.6', paddingTop: '20px' }}>
          Swipe left to open the menu!
        </p>
      </Page>
    );
  }
}

// patterns/splitter-outside-navigator-vue/src/Settings.vue
<template>
  <v-ons-page>
    <v-ons-toolbar>
      <div class="center">Navigator+Tabbar</div>
      <div class="right">
        <v-ons-toolbar-button @click="openMenu">
          <v-ons-icon icon="md-menu"></v-ons-icon>
        </v-ons-toolbar-button>
      </div>
    </v-ons-toolbar>
    <h2>Settings</h2>
    <p style="text-align: center; opacity: 0.6; padding-top: 20px;">
      Swipe left to open the menu!
    </p>
  </v-ons-page>
</template>

<script>
export default {
  props: ['openMenu']
}
</script>
