// patterns/navigator-outside-tabbar-react/src/AppTabbar.jsx
import React from 'react';
import { Toolbar, Page, Tabbar, Tab } from 'react-onsenui';

import Home from './Home'
import Cards from './Cards'
import Settings from './Settings'

export default class AppTabbar extends React.Component {
  renderToolbar() {
    return (
      <Toolbar>
        <div className="center">Navigator+Tabbar</div>
      </Toolbar>
    );
  }

  renderTabs(navigator) {
    return [
      {
        content: <Home key="home" navigator={this.props.navigator} />,
        tab: <Tab key="home" label="Home" icon="ion-home" />
      },
      {
        content: <Cards key="cards" navigator={this.props.navigator} />,
        tab: <Tab key="cards" label="Cards" icon="ion-card" badge="3" />
      },
      {
        content: <Settings key="settings" />,
        tab: <Tab key="settings" label="Settings" icon="ion-ios-cog" />
      }
    ];
  }

  render() {
    return (
      <Page renderToolbar={this.renderToolbar}>
        <Tabbar position='auto' index={0} renderTabs={this.renderTabs.bind(this)} />
      </Page>
    );
  }
}

// patterns/navigator-outside-tabbar-vue/src/AppTabbar.vue
<template>
  <v-ons-page>
    <v-ons-toolbar>
      <div class="center">Navigator+Tabbar</div>
    </v-ons-toolbar>
  
    <v-ons-tabbar position="auto" :tabs="tabs" :index.sync="activeIndex">
      <template slot="pages">
        <component v-for="tab in tabs" :is="tab.page" :key="tab.page" :page-stack="pageStack"></component>
      </template>
    </v-ons-tabbar>
  </v-ons-page>
</template>

<script>
import home from './Home';
import cards from './Cards';
import settings from './Settings';

export default {
  data() {
    return {
      activeIndex: 0,
      tabs: [
        {
          icon: 'ion-home',
          label: 'Home',
          page: home
        },
        {
          icon: 'ion-card',
          label: 'Cards',
          page: cards,
          badge: 3
        },
        {
          icon: 'ion-ios-cog',
          label: 'Settings',
          page: settings
        }
      ]
    }
  },
  props: ['pageStack']
}
</script>
