// patterns/navigator-outside-tabbar-react/src/Home.jsx
import React from 'react';
import { Page, Button } from 'react-onsenui';

import PageNav1 from './PageNav1';

export default class Home extends React.Component {
  pushPage() {
    this.props.navigator.pushPage({ component: PageNav1, props: { key: 'pageNav1' } });
  }

  render() {
    return (
      <Page>
        <h2>Home</h2>
        <div style={{ textAlign: 'center' }}>
          <br />
          <Button onClick={this.pushPage.bind(this)}>
            Push Page
          </Button>
        </div>
      </Page>
    );
  }
}

// patterns/navigator-outside-tabbar-vue/src/Home.vue
<template>
  <v-ons-page>
    <h2>Home</h2>
    <div style="text-align: center">
      <br>
      <v-ons-button @click="push">
        Push Page
      </v-ons-button>
    </div>
  </v-ons-page>
</template>

<script>
import pageNav1 from './PageNav1';
export default {
  methods: {
    push() {
      this.pageStack.push(pageNav1);
    }
  },
  props: ['pageStack']
}
</script>
