// patterns/splitter-outside-navigator-vue/src/PageNav1.vue
<template>
  <v-ons-page>
    <v-ons-toolbar>
      <div class="left">
        <v-ons-back-button>Back</v-ons-back-button>
      </div>
      <div class="center">{{ title }}</div>
      <div class="right">
        <v-ons-toolbar-button @click="openMenu">
          <v-ons-icon icon="md-menu"></v-ons-icon>
        </v-ons-toolbar-button>
      </div>
    </v-ons-toolbar>
    <div style="text-align: center">
      <h1>Custom Page</h1>
      <p>
        <v-ons-input modifier="underbar" placeholder="Title" float></v-ons-input>
      </p>
      <v-ons-button @click="push">
        Push Page
      </v-ons-button>
      <v-ons-button @click="pop">
        Pop Page
      </v-ons-button>
    </div>
    <p style="text-align: center; opacity: 0.6; padding-top: 20px;">
      Swipe left to open the menu!
    </p>
  </v-ons-page>
</template>

<script>
export default {
  beforeCreate: function () {
    this.pageNav1 = require('./PageNav1.vue');
  },
  created: function () {
    this.title = this.title && this.title !== '' ? this.title : 'Custom Page';
  },
  methods: {
    pop() {
      this.$emit('pop');
    },
    push() {
      var title = this.$el.querySelector('ons-input').value;
      var pageToPush = {
        extends: this.pageNav1,
        data() {
          return {
            title: title
          }
        }
      };
      this.$emit('push', pageToPush);
    }
  },
  props: ['openMenu']
}
</script>

// patterns/splitter-outside-navigator-react/src/PageNav1.jsx
import React from 'react';
import { Page, Toolbar, ToolbarButton, Icon, BackButton, Input, Button } from 'react-onsenui';

export default class PageNav1 extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      title: props.title ? props.title : 'Custom Page',
      nextTitle: null
    };
  }

  renderToolbar() {
    return (
      <Toolbar>
        <div className='left'><BackButton>Back</BackButton></div>
        <div className="center">{this.state.title}</div>
        <div className='right'>
          <ToolbarButton onClick={this.showMenu.bind(this)}>
            <Icon icon='ion-navicon, material:md-menu' />
          </ToolbarButton>
        </div>
      </Toolbar>
    );
  }

  showMenu() {
    this.props.showMenu();
  }

  pushPage() {
    this.props.navigator.pushPage({ component: PageNav1, props: { key: 'pageNav' + this.props.navigator.routes.length, title: this.state.nexTitle } });
  }

  popPage() {
    this.props.navigator.popPage();
  }

  render() {
    return (
      <Page renderToolbar={this.renderToolbar.bind(this)}>
        <div style={{ textAlign: 'center' }}>
          <h1>Custom Page</h1>
          <p>
            <Input modifier="underbar" placeholder="Title" float onChange={evt => this.setState({ nexTitle: evt.target.value })} ></Input>
          </p>
          <Button onClick={this.pushPage.bind(this)}>
            Push Page
          </Button>
          <Button onClick={this.popPage.bind(this)}>
            Pop Page
          </Button>
        </div>
        <p style={{ textAlign: 'center', opacity: '0.6', paddingTop: '20px' }}>
          Swipe left to open the menu!
        </p>
      </Page>
    );
  }
}
