// patterns/navigator-outside-tabbar-vue/src/Cards.vue
<template>
  <v-ons-page>
    <h2>Cards</h2>
    <v-ons-list-title>Card List</v-ons-list-title>
    <v-ons-list>
      <v-ons-list-item @click="push">Card One</v-ons-list-item>
      <v-ons-list-item @click="push">Card Two</v-ons-list-item>
      <v-ons-list-item @click="push">Card Three</v-ons-list-item>
    </v-ons-list>
  </v-ons-page>
</template>

<script>
import pageNav2 from './PageNav2';
export default {
  methods: {
    pop() {
      this.pageStack.pop();
    },
    push($event) {
      var cardTitle = $event.target.textContent;
      var pageToPush = {
        extends: pageNav2,
        data() {
          return {
            cardTitle: cardTitle
          }
        }
      };
      this.pageStack.push(pageToPush);
    }
  },
  props: ['pageStack']
}
</script>

// patterns/navigator-outside-tabbar-react/src/Cards.jsx
import React from 'react';
import { Page, ListTitle, List, ListItem } from 'react-onsenui';

import PageNav2 from './PageNav2';

export default class Cards extends React.Component {
  pushPage(event) {
    this.props.navigator.pushPage({ component: PageNav2, props: { key: 'pageNav2', cardTitle: event.target.textContent } });
  }

  render() {
    return (
      <Page>
        <h2>Cards</h2>
        
        <ListTitle>Card List</ListTitle>
        <List>
          <ListItem onClick={this.pushPage.bind(this)}>Card One</ListItem>
          <ListItem onClick={this.pushPage.bind(this)}>Card Two</ListItem>
          <ListItem onClick={this.pushPage.bind(this)}>Card Three</ListItem>
        </List>
      </Page>
    );
  }
}
