// patterns/navigator-outside-tabbar-vue/src/PageNav1.vue
<template>
  <v-ons-page>
    <v-ons-toolbar>
      <div class="left">
        <v-ons-back-button>Back</v-ons-back-button>
      </div>
      <div class="center">{{ title }}</div>
    </v-ons-toolbar>
    <div style="text-align: center">
      <h1>Custom Page</h1>
      <p>
        <v-ons-input modifier="underbar" placeholder="Title" float></v-ons-input>
      </p>
      <v-ons-button @click="push">
        Push Page
      </v-ons-button>
      <v-ons-button @click="pop">
        Pop Page
      </v-ons-button>
    </div>
  </v-ons-page>
</template>

<script>
export default {
  beforeCreate: function () {
    this.pageNav1 = require('./PageNav1.vue');
  },
  methods: {
    pop() {
      this.pageStack.pop();
    },
    push() {
      this.pageStack.push(this.pageNav1);
    }
  },
  props: {
    pageStack: Array,
    title: {
      type: String,
      default: 'Custom Page'
    }
  }
}
</script>

// patterns/navigator-outside-tabbar-react/src/PageNav1.jsx
import React from 'react';
import { Page, Toolbar, BackButton, Input, Button } from 'react-onsenui';

export default class PageNav1 extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      title: props.title ? props.title : 'Custom Page',
      nextTitle: null
    };
  }

  renderToolbar() {
    return (
      <Toolbar>
        <div className='left'><BackButton>Back</BackButton></div>
        <div className="center">{this.state.title}</div>
      </Toolbar>
    );
  }

  pushPage() {
    this.props.navigator.pushPage({ component: PageNav1, props: { key: 'pageNav' + this.props.navigator.routes.length, title: this.state.nexTitle } });
  }

  popPage() {
    this.props.navigator.popPage();
  }

  render() {
    return (
      <Page renderToolbar={this.renderToolbar.bind(this)}>
        <div style={{ textAlign: 'center' }}>
          <h1>Custom Page</h1>
          <p>
            <Input modifier="underbar" placeholder="Title" float onChange={evt => this.setState({ nexTitle: evt.target.value })} ></Input>
          </p>
          <Button onClick={this.pushPage.bind(this)}>
            Push Page
          </Button>
          <Button onClick={this.popPage.bind(this)}>
            Pop Page
          </Button>
        </div>
      </Page>
    );
  }
}
